#!/bin/sh
#
# Synchronizes all LetsEncrypt certificates to AWS IAM
#

for livecert in $(find /etc/letsencrypt/live/* -maxdepth 0 -type d) ; do
    CERTNAME=$(basename $livecert)

    if CERTDATA=$(aws iam get-server-certificate --server-certificate-name "${CERTNAME}" "$@") ; then
        echo "IAM server certificate for ${CERTNAME} already exists!"
        echo "If you need to update it, delete it from AWS and then re-run this script."
        exit 1
    fi

    aws iam upload-server-certificate \
        --server-certificate-name "${CERTNAME}" \
        --certificate-body "file:///etc/letsencrypt/live/${CERTNAME}/cert.pem"   \
        --private-key "file:///etc/letsencrypt/live/${CERTNAME}/privkey.pem"     \
        --certificate-chain "file:///etc/letsencrypt/live/${CERTNAME}/chain.pem" \
        --path "/cloudfront/${CERTNAME}/" \
        "$@"
done
